spring.data.mongodb.uri=mongodb+srv://sarthakgupta2303_db_user:Sarthak2025@finestay.i1f1d14.mongodb.net/?appName=finestay
spring.data.mongodb.database=TaskList
jwt.secret = abc123abc123efgquinjhetuinf17dhi
jwt.expiration = 86400000